<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\City;
use Illuminate\Support\Str;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = $this->getCityData();
        
        foreach ($cities as $index => $cityData) {
            City::updateOrCreate(
                ['slug' => $cityData['slug']],
                array_merge($cityData, [
                    'sort_order' => $index + 1,
                    'is_active' => true,
                    'country' => 'PK',
                    'meta_robots' => 'index, follow',
                ])
            );
        }
    }

    /**
     * Get all city data
     */
    private function getCityData(): array
    {
        return [
            // ==================== MAJOR CITIES (Featured) ====================
            [
                'name' => 'Karachi',
                'slug' => 'karachi',
                'lat' => 24.8608,
                'lng' => 67.0104,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Karachi | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Karachi. 24/7 emergency service available. Free quotation.',
            ],
            [
                'name' => 'Lahore',
                'slug' => 'lahore',
                'lat' => 31.5580,
                'lng' => 74.3507,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Lahore | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Lahore. 24/7 emergency service available. Free quotation.',
            ],
            [
                'name' => 'Islamabad',
                'slug' => 'islamabad',
                'lat' => 33.7215,
                'lng' => 73.0433,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Islamabad | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Islamabad. 24/7 emergency service available. Free quotation.',
            ],
            [
                'name' => 'Rawalpindi',
                'slug' => 'rawalpindi',
                'lat' => 33.5973,
                'lng' => 73.0479,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Rawalpindi | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Rawalpindi. 24/7 emergency service available. Free quotation.',
            ],
            [
                'name' => 'Peshawar',
                'slug' => 'peshawar',
                'lat' => 34.0080,
                'lng' => 71.5785,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Peshawar | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Peshawar. 24/7 emergency service available. Free quotation.',
            ],
            [
                'name' => 'Faisalabad',
                'slug' => 'faisalabad',
                'lat' => 31.4155,
                'lng' => 73.0897,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Faisalabad | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Faisalabad. 24/7 emergency service available. Free quotation.',
            ],
            [
                'name' => 'Multan',
                'slug' => 'multan',
                'lat' => 30.1968,
                'lng' => 71.4782,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Multan | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Multan. 24/7 emergency service available. Free quotation.',
            ],
            [
                'name' => 'Gujranwala',
                'slug' => 'gujranwala',
                'lat' => 32.1557,
                'lng' => 74.1871,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Gujranwala | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Gujranwala. 24/7 emergency service available. Free quotation.',
            ],
            [
                'name' => 'Sialkot',
                'slug' => 'sialkot',
                'lat' => 32.4927,
                'lng' => 74.5313,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Sialkot | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Sialkot. 24/7 emergency service available. Free quotation.',
            ],
            [
                'name' => 'Quetta',
                'slug' => 'quetta',
                'lat' => 30.1841,
                'lng' => 67.0014,
                'is_featured' => true,
                'meta_title' => 'Concrete Cutting Services in Quetta | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Quetta. 24/7 emergency service available. Free quotation.',
            ],

            // ==================== PROVINCIAL CAPITALS & MAJOR CITIES ====================
            [
                'name' => 'Hyderabad',
                'slug' => 'hyderabad',
                'lat' => 25.3924,
                'lng' => 68.3737,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Hyderabad | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Hyderabad. 24/7 emergency service available.',
            ],
            [
                'name' => 'Sukkur',
                'slug' => 'sukkur',
                'lat' => 27.7032,
                'lng' => 68.8589,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Sukkur | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Sukkur. 24/7 emergency service available.',
            ],
            [
                'name' => 'Bahawalpur',
                'slug' => 'bahawalpur',
                'lat' => 29.3978,
                'lng' => 71.6752,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Bahawalpur | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Bahawalpur. 24/7 emergency service available.',
            ],
            [
                'name' => 'Sargodha',
                'slug' => 'sargodha',
                'lat' => 32.0859,
                'lng' => 72.6742,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Sargodha | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Sargodha. 24/7 emergency service available.',
            ],
            [
                'name' => 'Sheikhupura',
                'slug' => 'sheikhupura',
                'lat' => 31.7129,
                'lng' => 73.9856,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Sheikhupura | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Sheikhupura. 24/7 emergency service available.',
            ],
            [
                'name' => 'Jhelum',
                'slug' => 'jhelum',
                'lat' => 32.9345,
                'lng' => 73.7310,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Jhelum | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Jhelum. 24/7 emergency service available.',
            ],
            [
                'name' => 'Mardan',
                'slug' => 'mardan',
                'lat' => 34.1979,
                'lng' => 72.0497,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Mardan | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Mardan. 24/7 emergency service available.',
            ],
            [
                'name' => 'Abbottabad',
                'slug' => 'abbottabad',
                'lat' => 34.1463,
                'lng' => 73.2117,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Abbottabad | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Abbottabad. 24/7 emergency service available.',
            ],
            [
                'name' => 'Mirpur Khas',
                'slug' => 'mirpur-khas',
                'lat' => 25.5276,
                'lng' => 69.0126,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Mirpur Khas | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Mirpur Khas. 24/7 emergency service available.',
            ],
            [
                'name' => 'Dera Ghazi Khan',
                'slug' => 'dera-ghazi-khan',
                'lat' => 30.0459,
                'lng' => 70.6403,
                'is_featured' => false,
                'meta_title' => 'Concrete Cutting Services in Dera Ghazi Khan | Professional Core Cutting',
                'meta_description' => 'Professional concrete cutting, core drilling, and wall saw cutting services in Dera Ghazi Khan. 24/7 emergency service available.',
            ],

            // ==================== ALL OTHER CITIES ====================
            [
                'name' => 'Adilpur',
                'slug' => 'adilpur',
                'lat' => 27.9368,
                'lng' => 69.3194,
            ],
            [
                'name' => 'Ahmadpur East',
                'slug' => 'ahmadpur-east',
                'lat' => 29.1427,
                'lng' => 71.2577,
            ],
            [
                'name' => 'Ahmadpur Sial',
                'slug' => 'ahmadpur-sial',
                'lat' => 30.6779,
                'lng' => 71.7434,
            ],
            [
                'name' => 'Akora',
                'slug' => 'akora',
                'lat' => 34.0034,
                'lng' => 72.1256,
            ],
            [
                'name' => 'Aliabad',
                'slug' => 'aliabad',
                'lat' => 36.3070,
                'lng' => 74.6155,
            ],
            [
                'name' => 'Alik Ghund',
                'slug' => 'alik-ghund',
                'lat' => 30.4898,
                'lng' => 67.5218,
            ],
            [
                'name' => 'Alipur',
                'slug' => 'alipur',
                'lat' => 29.3824,
                'lng' => 70.9111,
            ],
            [
                'name' => 'Alizai',
                'slug' => 'alizai',
                'lat' => 33.5361,
                'lng' => 70.3461,
            ],
            [
                'name' => 'Alpurai',
                'slug' => 'alpurai',
                'lat' => 34.9204,
                'lng' => 72.6327,
            ],
            [
                'name' => 'Aman Garh',
                'slug' => 'aman-garh',
                'lat' => 34.0058,
                'lng' => 71.9297,
            ],
            [
                'name' => 'Amirabad',
                'slug' => 'amirabad',
                'lat' => 34.1873,
                'lng' => 73.0908,
            ],
            [
                'name' => 'Arifwala',
                'slug' => 'arifwala',
                'lat' => 30.2906,
                'lng' => 73.0657,
            ],
            [
                'name' => 'Ashanagro Koto',
                'slug' => 'ashanagro-koto',
                'lat' => 34.1077,
                'lng' => 72.2452,
            ],
            [
                'name' => 'Athmuqam',
                'slug' => 'athmuqam',
                'lat' => 34.5717,
                'lng' => 73.8972,
            ],
            [
                'name' => 'Attock City',
                'slug' => 'attock-city',
                'lat' => 33.7667,
                'lng' => 72.3598,
            ],
            [
                'name' => 'Awaran',
                'slug' => 'awaran',
                'lat' => 26.4568,
                'lng' => 65.2314,
            ],
            [
                'name' => 'Baddomalhi',
                'slug' => 'baddomalhi',
                'lat' => 31.9904,
                'lng' => 74.6641,
            ],
            [
                'name' => 'Badin',
                'slug' => 'badin',
                'lat' => 24.6560,
                'lng' => 68.8370,
            ],
            [
                'name' => 'Baffa',
                'slug' => 'baffa',
                'lat' => 34.4377,
                'lng' => 73.2237,
            ],
            [
                'name' => 'Bagarji',
                'slug' => 'bagarji',
                'lat' => 27.7543,
                'lng' => 68.7587,
            ],
            [
                'name' => 'Bagh',
                'slug' => 'bagh',
                'lat' => 33.9811,
                'lng' => 73.7761,
            ],
            [
                'name' => 'Bahawalnagar',
                'slug' => 'bahawalnagar',
                'lat' => 30.5508,
                'lng' => 73.3908,
            ],
            [
                'name' => 'Bakhri Ahmad Khan',
                'slug' => 'bakhri-ahmad-khan',
                'lat' => 30.7359,
                'lng' => 70.8380,
            ],
            [
                'name' => 'Bandhi',
                'slug' => 'bandhi',
                'lat' => 26.5876,
                'lng' => 68.3022,
            ],
            [
                'name' => 'Bannu',
                'slug' => 'bannu',
                'lat' => 32.9853,
                'lng' => 70.6040,
            ],
            [
                'name' => 'Barishal',
                'slug' => 'barishal',
                'lat' => 36.3216,
                'lng' => 74.6950,
            ],
            [
                'name' => 'Barkhan',
                'slug' => 'barkhan',
                'lat' => 29.8977,
                'lng' => 69.5256,
            ],
            [
                'name' => 'Basirpur',
                'slug' => 'basirpur',
                'lat' => 30.5776,
                'lng' => 73.8391,
            ],
            [
                'name' => 'Basti Dosa',
                'slug' => 'basti-dosa',
                'lat' => 30.7877,
                'lng' => 70.8685,
            ],
            [
                'name' => 'Bat Khela',
                'slug' => 'bat-khela',
                'lat' => 34.6178,
                'lng' => 71.9725,
            ],
            [
                'name' => 'Battagram',
                'slug' => 'battagram',
                'lat' => 34.6772,
                'lng' => 73.0233,
            ],
            [
                'name' => 'Begowala',
                'slug' => 'begowala',
                'lat' => 32.4382,
                'lng' => 74.2679,
            ],
            [
                'name' => 'Bela',
                'slug' => 'bela',
                'lat' => 26.2272,
                'lng' => 66.3118,
            ],
            [
                'name' => 'Berani',
                'slug' => 'berani',
                'lat' => 25.7850,
                'lng' => 68.8075,
            ],
            [
                'name' => 'Bhag',
                'slug' => 'bhag',
                'lat' => 29.0417,
                'lng' => 67.8239,
            ],
            [
                'name' => 'Bhakkar',
                'slug' => 'bhakkar',
                'lat' => 31.6269,
                'lng' => 71.0647,
            ],
            [
                'name' => 'Bhalwal',
                'slug' => 'bhalwal',
                'lat' => 32.2658,
                'lng' => 72.8981,
            ],
            [
                'name' => 'Bhan',
                'slug' => 'bhan',
                'lat' => 26.5583,
                'lng' => 67.7214,
            ],
            [
                'name' => 'Bhawana',
                'slug' => 'bhawana',
                'lat' => 31.5688,
                'lng' => 72.6492,
            ],
            [
                'name' => 'Bhera',
                'slug' => 'bhera',
                'lat' => 32.4821,
                'lng' => 72.9087,
            ],
            [
                'name' => 'Bhimbar',
                'slug' => 'bhimbar',
                'lat' => 32.9747,
                'lng' => 74.0785,
            ],
            [
                'name' => 'Bhiria',
                'slug' => 'bhiria',
                'lat' => 26.9104,
                'lng' => 68.1947,
            ],
            [
                'name' => 'Bhit Shah',
                'slug' => 'bhit-shah',
                'lat' => 25.8057,
                'lng' => 68.4914,
            ],
            [
                'name' => 'Bhopalwala',
                'slug' => 'bhopalwala',
                'lat' => 32.4297,
                'lng' => 74.3635,
            ],
            [
                'name' => 'Bozdar Wada',
                'slug' => 'bozdar-wada',
                'lat' => 27.1830,
                'lng' => 68.6358,
            ],
            [
                'name' => 'Bulri',
                'slug' => 'bulri',
                'lat' => 24.8667,
                'lng' => 68.3333,
            ],
            [
                'name' => 'Būrewāla',
                'slug' => 'burewala',
                'lat' => 30.1667,
                'lng' => 72.6500,
            ],
            [
                'name' => 'Chak',
                'slug' => 'chak',
                'lat' => 27.8584,
                'lng' => 68.8338,
            ],
            [
                'name' => 'Chak Azam Sahu',
                'slug' => 'chak-azam-sahu',
                'lat' => 30.7520,
                'lng' => 73.0283,
            ],
            [
                'name' => 'Chak Five Hundred Seventy-five',
                'slug' => 'chak-five-hundred-seventy-five',
                'lat' => 31.5451,
                'lng' => 73.8289,
            ],
            [
                'name' => 'Chak Jhumra',
                'slug' => 'chak-jhumra',
                'lat' => 31.5681,
                'lng' => 73.1832,
            ],
            [
                'name' => 'Chak One Hundred Twenty Nine Left',
                'slug' => 'chak-one-hundred-twenty-nine-left',
                'lat' => 30.4292,
                'lng' => 73.0452,
            ],
            [
                'name' => 'Chak Thirty-one -Eleven Left',
                'slug' => 'chak-thirty-one-eleven-left',
                'lat' => 30.4239,
                'lng' => 72.6974,
            ],
            [
                'name' => 'Chak Two Hundred Forty-nine Thal Development Authority',
                'slug' => 'chak-two-hundred-forty-nine-thal',
                'lat' => 31.1777,
                'lng' => 71.2048,
            ],
            [
                'name' => 'Chakwal',
                'slug' => 'chakwal',
                'lat' => 32.9329,
                'lng' => 72.8539,
            ],
            [
                'name' => 'Chaman',
                'slug' => 'chaman',
                'lat' => 30.9177,
                'lng' => 66.4526,
            ],
            [
                'name' => 'Chamber',
                'slug' => 'chamber',
                'lat' => 25.2936,
                'lng' => 68.8118,
            ],
            [
                'name' => 'Charsadda',
                'slug' => 'charsadda',
                'lat' => 34.1482,
                'lng' => 71.7406,
            ],
            [
                'name' => 'Chawinda',
                'slug' => 'chawinda',
                'lat' => 32.3443,
                'lng' => 74.7051,
            ],
            [
                'name' => 'Chenab Nagar',
                'slug' => 'chenab-nagar',
                'lat' => 31.7551,
                'lng' => 72.9140,
            ],
            [
                'name' => 'Cherat Cantonement',
                'slug' => 'cherat-cantonement',
                'lat' => 33.8234,
                'lng' => 71.8929,
            ],
            [
                'name' => 'Chhor',
                'slug' => 'chhor',
                'lat' => 25.5126,
                'lng' => 69.7844,
            ],
            [
                'name' => 'Chichawatni',
                'slug' => 'chichawatni',
                'lat' => 30.5301,
                'lng' => 72.6916,
            ],
            [
                'name' => 'Chilas',
                'slug' => 'chilas',
                'lat' => 35.4129,
                'lng' => 74.1041,
            ],
            [
                'name' => 'Chiniot',
                'slug' => 'chiniot',
                'lat' => 31.7209,
                'lng' => 72.9784,
            ],
            [
                'name' => 'Chishtian',
                'slug' => 'chishtian',
                'lat' => 29.7971,
                'lng' => 72.8577,
            ],
            [
                'name' => 'Chitral',
                'slug' => 'chitral',
                'lat' => 35.8518,
                'lng' => 71.7864,
            ],
            [
                'name' => 'Choa Saidan Shah',
                'slug' => 'choa-saidan-shah',
                'lat' => 32.7196,
                'lng' => 72.9863,
            ],
            [
                'name' => 'Chowki Jamali',
                'slug' => 'chowki-jamali',
                'lat' => 28.0194,
                'lng' => 67.9208,
            ],
            [
                'name' => 'Chuchar-kana Mandi',
                'slug' => 'chuchar-kana-mandi',
                'lat' => 31.7500,
                'lng' => 73.8000,
            ],
            [
                'name' => 'Chuhar Jamali',
                'slug' => 'chuhar-jamali',
                'lat' => 24.3944,
                'lng' => 67.9930,
            ],
            [
                'name' => 'Chunian',
                'slug' => 'chunian',
                'lat' => 30.9662,
                'lng' => 73.9791,
            ],
            [
                'name' => 'Dadhar',
                'slug' => 'dadhar',
                'lat' => 29.4749,
                'lng' => 67.6517,
            ],
            [
                'name' => 'Dadu',
                'slug' => 'dadu',
                'lat' => 26.7303,
                'lng' => 67.7769,
            ],
            [
                'name' => 'Daggar',
                'slug' => 'daggar',
                'lat' => 34.5111,
                'lng' => 72.4844,
            ],
            [
                'name' => 'Daira Din Panah',
                'slug' => 'daira-din-panah',
                'lat' => 30.5705,
                'lng' => 70.9372,
            ],
            [
                'name' => 'Dajal',
                'slug' => 'dajal',
                'lat' => 29.5577,
                'lng' => 70.3761,
            ],
            [
                'name' => 'Dalbandin',
                'slug' => 'dalbandin',
                'lat' => 28.8885,
                'lng' => 64.4062,
            ],
            [
                'name' => 'Dandot RS',
                'slug' => 'dandot-rs',
                'lat' => 32.6417,
                'lng' => 72.9750,
            ],
            [
                'name' => 'Daromehar',
                'slug' => 'daromehar',
                'lat' => 24.7938,
                'lng' => 68.1798,
            ],
            [
                'name' => 'Darya Khan',
                'slug' => 'darya-khan',
                'lat' => 31.7845,
                'lng' => 71.1020,
            ],
            [
                'name' => 'Darya Khan Marri',
                'slug' => 'darya-khan-marri',
                'lat' => 26.6777,
                'lng' => 68.2867,
            ],
            [
                'name' => 'Daska Kalan',
                'slug' => 'daska-kalan',
                'lat' => 32.3242,
                'lng' => 74.3504,
            ],
            [
                'name' => 'Dasu',
                'slug' => 'dasu',
                'lat' => 35.2917,
                'lng' => 73.2906,
            ],
            [
                'name' => 'Daud Khel',
                'slug' => 'daud-khel',
                'lat' => 32.8753,
                'lng' => 71.5712,
            ],
            [
                'name' => 'Daulatpur',
                'slug' => 'daulatpur',
                'lat' => 26.5016,
                'lng' => 67.9708,
            ],
            [
                'name' => 'Daultala',
                'slug' => 'daultala',
                'lat' => 33.1928,
                'lng' => 73.1410,
            ],
            [
                'name' => 'Daur',
                'slug' => 'daur',
                'lat' => 26.4553,
                'lng' => 68.3184,
            ],
            [
                'name' => 'Dera Allahyar',
                'slug' => 'dera-allahyar',
                'lat' => 28.3735,
                'lng' => 68.3508,
            ],
            [
                'name' => 'Dera Bugti',
                'slug' => 'dera-bugti',
                'lat' => 29.0362,
                'lng' => 69.1585,
            ],
            [
                'name' => 'Dera Ismail Khan',
                'slug' => 'dera-ismail-khan',
                'lat' => 31.8313,
                'lng' => 70.9017,
            ],
            [
                'name' => 'Dera Murad Jamali',
                'slug' => 'dera-murad-jamali',
                'lat' => 28.5466,
                'lng' => 68.2231,
            ],
            [
                'name' => 'Dhanot',
                'slug' => 'dhanot',
                'lat' => 29.5799,
                'lng' => 71.7521,
            ],
            [
                'name' => 'Dhaunkal',
                'slug' => 'dhaunkal',
                'lat' => 32.4061,
                'lng' => 74.1371,
            ],
            [
                'name' => 'Dhoro Naro',
                'slug' => 'dhoro-naro',
                'lat' => 25.5048,
                'lng' => 69.5709,
            ],
            [
                'name' => 'Digri',
                'slug' => 'digri',
                'lat' => 25.1566,
                'lng' => 69.1110,
            ],
            [
                'name' => 'Dijkot',
                'slug' => 'dijkot',
                'lat' => 31.2174,
                'lng' => 72.9962,
            ],
            [
                'name' => 'Dinan Bashnoian Wala',
                'slug' => 'dinan-bashnoian-wala',
                'lat' => 29.7658,
                'lng' => 73.2656,
            ],
            [
                'name' => 'Dinga',
                'slug' => 'dinga',
                'lat' => 32.6410,
                'lng' => 73.7204,
            ],
            [
                'name' => 'Dipalpur',
                'slug' => 'dipalpur',
                'lat' => 30.6698,
                'lng' => 73.6531,
            ],
            [
                'name' => 'Diplo',
                'slug' => 'diplo',
                'lat' => 24.4669,
                'lng' => 69.5811,
            ],
            [
                'name' => 'Doaba',
                'slug' => 'doaba',
                'lat' => 33.4245,
                'lng' => 70.7368,
            ],
            [
                'name' => 'Dokri',
                'slug' => 'dokri',
                'lat' => 27.3742,
                'lng' => 68.0972,
            ],
            [
                'name' => 'Duki',
                'slug' => 'duki',
                'lat' => 30.1531,
                'lng' => 68.5732,
            ],
            [
                'name' => 'Dullewala',
                'slug' => 'dullewala',
                'lat' => 31.8344,
                'lng' => 71.4364,
            ],
            [
                'name' => 'Dunga Bunga',
                'slug' => 'dunga-bunga',
                'lat' => 29.7498,
                'lng' => 73.2429,
            ],
            [
                'name' => 'Dunyapur',
                'slug' => 'dunyapur',
                'lat' => 29.8028,
                'lng' => 71.7434,
            ],
            [
                'name' => 'Eidgah',
                'slug' => 'eidgah',
                'lat' => 35.3471,
                'lng' => 74.8563,
            ],
            [
                'name' => 'Eminabad',
                'slug' => 'eminabad',
                'lat' => 32.0424,
                'lng' => 74.2600,
            ],
            [
                'name' => 'Faqirwali',
                'slug' => 'faqirwali',
                'lat' => 29.4680,
                'lng' => 73.0349,
            ],
            [
                'name' => 'Faruka',
                'slug' => 'faruka',
                'lat' => 31.8864,
                'lng' => 72.4136,
            ],
            [
                'name' => 'Fazilpur',
                'slug' => 'fazilpur',
                'lat' => 32.1763,
                'lng' => 75.0658,
            ],
            [
                'name' => 'Fort Abbas',
                'slug' => 'fort-abbas',
                'lat' => 29.1934,
                'lng' => 72.8553,
            ],
            [
                'name' => 'Gadani',
                'slug' => 'gadani',
                'lat' => 25.1185,
                'lng' => 66.7299,
            ],
            [
                'name' => 'Gakuch',
                'slug' => 'gakuch',
                'lat' => 36.1768,
                'lng' => 73.7638,
            ],
            [
                'name' => 'Gambat',
                'slug' => 'gambat',
                'lat' => 27.3517,
                'lng' => 68.5215,
            ],
            [
                'name' => 'Gandava',
                'slug' => 'gandava',
                'lat' => 28.6132,
                'lng' => 67.4856,
            ],
            [
                'name' => 'Garh Maharaja',
                'slug' => 'garh-maharaja',
                'lat' => 30.8338,
                'lng' => 71.9049,
            ],
            [
                'name' => 'Garhi Khairo',
                'slug' => 'garhi-khairo',
                'lat' => 28.0603,
                'lng' => 67.9803,
            ],
            [
                'name' => 'Garhiyasin',
                'slug' => 'garhiyasin',
                'lat' => 27.9063,
                'lng' => 68.5121,
            ],
            [
                'name' => 'Gharo',
                'slug' => 'gharo',
                'lat' => 24.7418,
                'lng' => 67.5853,
            ],
            [
                'name' => 'Ghauspur',
                'slug' => 'ghauspur',
                'lat' => 28.1388,
                'lng' => 69.0825,
            ],
            [
                'name' => 'Ghotki',
                'slug' => 'ghotki',
                'lat' => 28.0044,
                'lng' => 69.3157,
            ],
            [
                'name' => 'Gilgit',
                'slug' => 'gilgit',
                'lat' => 35.9187,
                'lng' => 74.3125,
            ],
            [
                'name' => 'Gojra',
                'slug' => 'gojra',
                'lat' => 31.1493,
                'lng' => 72.6832,
            ],
            [
                'name' => 'Goth Garelo',
                'slug' => 'goth-garelo',
                'lat' => 27.4352,
                'lng' => 68.0757,
            ],
            [
                'name' => 'Goth Phulji',
                'slug' => 'goth-phulji',
                'lat' => 26.8810,
                'lng' => 67.6824,
            ],
            [
                'name' => 'Goth Radhan',
                'slug' => 'goth-radhan',
                'lat' => 27.1985,
                'lng' => 67.9535,
            ],
            [
                'name' => 'Gujar Khan',
                'slug' => 'gujar-khan',
                'lat' => 33.2541,
                'lng' => 73.3043,
            ],
            [
                'name' => 'Gujrat',
                'slug' => 'gujrat',
                'lat' => 32.5742,
                'lng' => 74.0754,
            ],
            [
                'name' => 'Gulishah Kach',
                'slug' => 'gulishah-kach',
                'lat' => 32.6709,
                'lng' => 70.3392,
            ],
            [
                'name' => 'Gwadar',
                'slug' => 'gwadar',
                'lat' => 25.1216,
                'lng' => 62.3254,
            ],
            [
                'name' => 'Hadali',
                'slug' => 'hadali',
                'lat' => 32.6404,
                'lng' => 74.5690,
            ],
            [
                'name' => 'Hafizabad',
                'slug' => 'hafizabad',
                'lat' => 32.0710,
                'lng' => 73.6880,
            ],
            [
                'name' => 'Hala',
                'slug' => 'hala',
                'lat' => 25.8146,
                'lng' => 68.4220,
            ],
            [
                'name' => 'Hangu',
                'slug' => 'hangu',
                'lat' => 33.5320,
                'lng' => 71.0595,
            ],
            [
                'name' => 'Haripur',
                'slug' => 'haripur',
                'lat' => 33.9978,
                'lng' => 72.9349,
            ],
            [
                'name' => 'Harnai',
                'slug' => 'harnai',
                'lat' => 30.1008,
                'lng' => 67.9382,
            ],
            [
                'name' => 'Harnoli',
                'slug' => 'harnoli',
                'lat' => 32.2787,
                'lng' => 71.5543,
            ],
            [
                'name' => 'Harunabad',
                'slug' => 'harunabad',
                'lat' => 29.6121,
                'lng' => 73.1380,
            ],
            [
                'name' => 'Hasilpur',
                'slug' => 'hasilpur',
                'lat' => 29.6922,
                'lng' => 72.5457,
            ],
            [
                'name' => 'Hattian Bala',
                'slug' => 'hattian-bala',
                'lat' => 34.1691,
                'lng' => 73.7432,
            ],
            [
                'name' => 'Haveli Lakha',
                'slug' => 'haveli-lakha',
                'lat' => 30.4510,
                'lng' => 73.6937,
            ],
            [
                'name' => 'Havelian',
                'slug' => 'havelian',
                'lat' => 34.0535,
                'lng' => 73.1599,
            ],
            [
                'name' => 'Hazro City',
                'slug' => 'hazro-city',
                'lat' => 33.9099,
                'lng' => 72.4918,
            ],
            [
                'name' => 'Hingorja',
                'slug' => 'hingorja',
                'lat' => 27.2109,
                'lng' => 68.4160,
            ],
            [
                'name' => 'Hujra Shah Muqim',
                'slug' => 'hujra-shah-muqim',
                'lat' => 30.7417,
                'lng' => 73.8233,
            ],
            [
                'name' => 'Islamkot',
                'slug' => 'islamkot',
                'lat' => 24.6990,
                'lng' => 70.1798,
            ],
            [
                'name' => 'Jacobabad',
                'slug' => 'jacobabad',
                'lat' => 28.2819,
                'lng' => 68.4376,
            ],
            [
                'name' => 'Jahanian Shah',
                'slug' => 'jahanian-shah',
                'lat' => 31.8054,
                'lng' => 72.2774,
            ],
            [
                'name' => 'Jalalpur Jattan',
                'slug' => 'jalalpur-jattan',
                'lat' => 32.6412,
                'lng' => 74.2056,
            ],
            [
                'name' => 'Jalalpur Pirwala',
                'slug' => 'jalalpur-pirwala',
                'lat' => 29.5051,
                'lng' => 71.2220,
            ],
            [
                'name' => 'Jampur',
                'slug' => 'jampur',
                'lat' => 29.6424,
                'lng' => 70.5952,
            ],
            [
                'name' => 'Jamshoro',
                'slug' => 'jamshoro',
                'lat' => 25.4361,
                'lng' => 68.2802,
            ],
            [
                'name' => 'Jand',
                'slug' => 'jand',
                'lat' => 33.4330,
                'lng' => 72.0188,
            ],
            [
                'name' => 'Jandiala Sher Khan',
                'slug' => 'jandiala-sher-khan',
                'lat' => 31.8210,
                'lng' => 73.9182,
            ],
            [
                'name' => 'Jaranwala',
                'slug' => 'jaranwala',
                'lat' => 31.3332,
                'lng' => 73.4187,
            ],
            [
                'name' => 'Jati',
                'slug' => 'jati',
                'lat' => 24.3549,
                'lng' => 68.2673,
            ],
            [
                'name' => 'Jatoi Shimali',
                'slug' => 'jatoi-shimali',
                'lat' => 29.5183,
                'lng' => 70.8447,
            ],
            [
                'name' => 'Jauharabad',
                'slug' => 'jauharabad',
                'lat' => 32.2902,
                'lng' => 72.2818,
            ],
            [
                'name' => 'Jhang City',
                'slug' => 'jhang-city',
                'lat' => 31.3057,
                'lng' => 72.3259,
            ],
            [
                'name' => 'Jhang Sadr',
                'slug' => 'jhang-sadr',
                'lat' => 31.2698,
                'lng' => 72.3169,
            ],
            [
                'name' => 'Jhawarian',
                'slug' => 'jhawarian',
                'lat' => 32.3619,
                'lng' => 72.6228,
            ],
            [
                'name' => 'Jhol',
                'slug' => 'jhol',
                'lat' => 25.9553,
                'lng' => 68.8887,
            ],
            [
                'name' => 'Jiwani',
                'slug' => 'jiwani',
                'lat' => 25.0485,
                'lng' => 61.7457,
            ],
            [
                'name' => 'Johi',
                'slug' => 'johi',
                'lat' => 26.6923,
                'lng' => 67.6143,
            ],
            [
                'name' => 'Jām Sāhib',
                'slug' => 'jam-sahib',
                'lat' => 26.2958,
                'lng' => 68.6292,
            ],
            [
                'name' => 'Kabirwala',
                'slug' => 'kabirwala',
                'lat' => 30.4047,
                'lng' => 71.8627,
            ],
            [
                'name' => 'Kadhan',
                'slug' => 'kadhan',
                'lat' => 24.4804,
                'lng' => 68.9855,
            ],
            [
                'name' => 'Kahna Nau',
                'slug' => 'kahna-nau',
                'lat' => 31.3671,
                'lng' => 74.3690,
            ],
            [
                'name' => 'Kahror Pakka',
                'slug' => 'kahror-pakka',
                'lat' => 29.6243,
                'lng' => 71.9144,
            ],
            [
                'name' => 'Kahuta',
                'slug' => 'kahuta',
                'lat' => 33.5918,
                'lng' => 73.3874,
            ],
            [
                'name' => 'Kakad Wari Dir Upper',
                'slug' => 'kakad-wari-dir-upper',
                'lat' => 34.9980,
                'lng' => 72.0730,
            ],
            [
                'name' => 'Kalabagh',
                'slug' => 'kalabagh',
                'lat' => 32.9616,
                'lng' => 71.5464,
            ],
            [
                'name' => 'Kalaswala',
                'slug' => 'kalaswala',
                'lat' => 32.2008,
                'lng' => 74.6486,
            ],
            [
                'name' => 'Kalat',
                'slug' => 'kalat',
                'lat' => 29.0266,
                'lng' => 66.5936,
            ],
            [
                'name' => 'Kaleke Mandi',
                'slug' => 'kaleke-mandi',
                'lat' => 31.9760,
                'lng' => 73.6000,
            ],
            [
                'name' => 'Kallar Kahar',
                'slug' => 'kallar-kahar',
                'lat' => 32.7800,
                'lng' => 72.6979,
            ],
            [
                'name' => 'Kalur Kot',
                'slug' => 'kalur-kot',
                'lat' => 32.1551,
                'lng' => 71.2663,
            ],
            [
                'name' => 'Kamalia',
                'slug' => 'kamalia',
                'lat' => 30.7271,
                'lng' => 72.6461,
            ],
            [
                'name' => 'Kamar Mushani',
                'slug' => 'kamar-mushani',
                'lat' => 32.8432,
                'lng' => 71.3619,
            ],
            [
                'name' => 'Kambar',
                'slug' => 'kambar',
                'lat' => 27.5875,
                'lng' => 68.0007,
            ],
            [
                'name' => 'Kamoke',
                'slug' => 'kamoke',
                'lat' => 31.9753,
                'lng' => 74.2230,
            ],
            [
                'name' => 'Kamra',
                'slug' => 'kamra',
                'lat' => 33.7470,
                'lng' => 73.5123,
            ],
            [
                'name' => 'Kandhkot',
                'slug' => 'kandhkot',
                'lat' => 28.2457,
                'lng' => 69.1797,
            ],
            [
                'name' => 'Kandiari',
                'slug' => 'kandiari',
                'lat' => 26.9155,
                'lng' => 68.5219,
            ],
            [
                'name' => 'Kandiaro',
                'slug' => 'kandiaro',
                'lat' => 27.0592,
                'lng' => 68.2102,
            ],
            [
                'name' => 'Kanganpur',
                'slug' => 'kanganpur',
                'lat' => 30.7647,
                'lng' => 74.1229,
            ],
            [
                'name' => 'Karak',
                'slug' => 'karak',
                'lat' => 33.1163,
                'lng' => 71.0935,
            ],
            [
                'name' => 'Karaundi',
                'slug' => 'karaundi',
                'lat' => 26.8971,
                'lng' => 68.4064,
            ],
            [
                'name' => 'Kario Ghanwar',
                'slug' => 'kario-ghanwar',
                'lat' => 24.8082,
                'lng' => 68.6048,
            ],
            [
                'name' => 'Karor',
                'slug' => 'karor',
                'lat' => 31.2246,
                'lng' => 70.9515,
            ],
            [
                'name' => 'Kashmor',
                'slug' => 'kashmor',
                'lat' => 28.4326,
                'lng' => 69.5836,
            ],
            [
                'name' => 'Kasur',
                'slug' => 'kasur',
                'lat' => 31.1187,
                'lng' => 74.4503,
            ],
            [
                'name' => 'Keshupur',
                'slug' => 'keshupur',
                'lat' => 32.2600,
                'lng' => 72.5000,
            ],
            [
                'name' => 'Keti Bandar',
                'slug' => 'keti-bandar',
                'lat' => 24.1442,
                'lng' => 67.4509,
            ],
            [
                'name' => 'Khadan Khak',
                'slug' => 'khadan-khak',
                'lat' => 30.7524,
                'lng' => 67.7113,
            ],
            [
                'name' => 'Khadro',
                'slug' => 'khadro',
                'lat' => 26.1471,
                'lng' => 68.7178,
            ],
            [
                'name' => 'Khairpur',
                'slug' => 'khairpur',
                'lat' => 28.0644,
                'lng' => 69.7036,
            ],
            [
                'name' => 'Khairpur Mir’s',
                'slug' => 'khairpur-mirs',
                'lat' => 27.5295,
                'lng' => 68.7592,
            ],
            [
                'name' => 'Khairpur Nathan Shah',
                'slug' => 'khairpur-nathan-shah',
                'lat' => 27.0906,
                'lng' => 67.7349,
            ],
            [
                'name' => 'Khairpur Tamewah',
                'slug' => 'khairpur-tamewah',
                'lat' => 29.5814,
                'lng' => 72.2380,
            ],
            [
                'name' => 'Khalabat',
                'slug' => 'khalabat',
                'lat' => 34.0600,
                'lng' => 72.8896,
            ],
            [
                'name' => 'Khandowa',
                'slug' => 'khandowa',
                'lat' => 32.7426,
                'lng' => 72.7348,
            ],
            [
                'name' => 'Khanewal',
                'slug' => 'khanewal',
                'lat' => 30.3017,
                'lng' => 71.9321,
            ],
            [
                'name' => 'Khangah Dogran',
                'slug' => 'khangah-dogran',
                'lat' => 31.8329,
                'lng' => 73.6221,
            ],
            [
                'name' => 'Khangarh',
                'slug' => 'khangarh',
                'lat' => 29.9145,
                'lng' => 71.1607,
            ],
            [
                'name' => 'Khanpur',
                'slug' => 'khanpur',
                'lat' => 28.6474,
                'lng' => 70.6569,
            ],
            [
                'name' => 'Khanpur Mahar',
                'slug' => 'khanpur-mahar',
                'lat' => 27.8409,
                'lng' => 69.4130,
            ],
            [
                'name' => 'Kharan',
                'slug' => 'kharan',
                'lat' => 28.5846,
                'lng' => 65.4150,
            ],
            [
                'name' => 'Kharian',
                'slug' => 'kharian',
                'lat' => 32.8161,
                'lng' => 73.8870,
            ],
            [
                'name' => 'Khewra',
                'slug' => 'khewra',
                'lat' => 32.6491,
                'lng' => 73.0106,
            ],
            [
                'name' => 'Khurrianwala',
                'slug' => 'khurrianwala',
                'lat' => 31.4994,
                'lng' => 73.2676,
            ],
            [
                'name' => 'Khushāb',
                'slug' => 'khushab',
                'lat' => 32.2967,
                'lng' => 72.3525,
            ],
            [
                'name' => 'Khuzdar',
                'slug' => 'khuzdar',
                'lat' => 27.8119,
                'lng' => 66.6110,
            ],
            [
                'name' => 'Kohat',
                'slug' => 'kohat',
                'lat' => 33.5820,
                'lng' => 71.4493,
            ],
            [
                'name' => 'Kohlu',
                'slug' => 'kohlu',
                'lat' => 29.8965,
                'lng' => 69.2532,
            ],
            [
                'name' => 'Kot Addu',
                'slug' => 'kot-addu',
                'lat' => 30.4691,
                'lng' => 70.9670,
            ],
            [
                'name' => 'Kot Diji',
                'slug' => 'kot-diji',
                'lat' => 27.3416,
                'lng' => 68.7082,
            ],
            [
                'name' => 'Kot Ghulam Muhammad',
                'slug' => 'kot-ghulam-muhammad',
                'lat' => 32.3331,
                'lng' => 74.5469,
            ],
            [
                'name' => 'Kot Malik Barkhurdar',
                'slug' => 'kot-malik-barkhurdar',
                'lat' => 30.2038,
                'lng' => 66.9872,
            ],
            [
                'name' => 'Kot Mumin',
                'slug' => 'kot-mumin',
                'lat' => 32.1884,
                'lng' => 73.0299,
            ],
            [
                'name' => 'Kot Radha Kishan',
                'slug' => 'kot-radha-kishan',
                'lat' => 31.1707,
                'lng' => 74.1013,
            ],
            [
                'name' => 'Kot Rajkour',
                'slug' => 'kot-rajkour',
                'lat' => 32.4121,
                'lng' => 74.6286,
            ],
            [
                'name' => 'Kot Samaba',
                'slug' => 'kot-samaba',
                'lat' => 28.5521,
                'lng' => 70.4684,
            ],
            [
                'name' => 'Kot Sultan',
                'slug' => 'kot-sultan',
                'lat' => 30.7737,
                'lng' => 70.9313,
            ],
            [
                'name' => 'Kotli',
                'slug' => 'kotli',
                'lat' => 33.5184,
                'lng' => 73.9022,
            ],
            [
                'name' => 'Kotli Loharan',
                'slug' => 'kotli-loharan',
                'lat' => 32.5889,
                'lng' => 74.4947,
            ],
            [
                'name' => 'Kotri',
                'slug' => 'kotri',
                'lat' => 25.3657,
                'lng' => 68.3083,
            ],
            [
                'name' => 'Kulachi',
                'slug' => 'kulachi',
                'lat' => 31.9306,
                'lng' => 70.4596,
            ],
            [
                'name' => 'Kundian',
                'slug' => 'kundian',
                'lat' => 32.4578,
                'lng' => 71.4789,
            ],
            [
                'name' => 'Kunjah',
                'slug' => 'kunjah',
                'lat' => 32.5298,
                'lng' => 73.9749,
            ],
            [
                'name' => 'Kunri',
                'slug' => 'kunri',
                'lat' => 25.1787,
                'lng' => 69.5657,
            ],
            [
                'name' => 'Lachi',
                'slug' => 'lachi',
                'lat' => 33.3829,
                'lng' => 71.3373,
            ],
            [
                'name' => 'Ladhewala Waraich',
                'slug' => 'ladhewala-waraich',
                'lat' => 32.1569,
                'lng' => 74.1156,
            ],
            [
                'name' => 'Lakhi',
                'slug' => 'lakhi',
                'lat' => 27.8488,
                'lng' => 68.6997,
            ],
            [
                'name' => 'Lakki',
                'slug' => 'lakki',
                'lat' => 32.6072,
                'lng' => 70.9123,
            ],
            [
                'name' => 'Lala Musa',
                'slug' => 'lala-musa',
                'lat' => 32.7014,
                'lng' => 73.9575,
            ],
            [
                'name' => 'Lalian',
                'slug' => 'lalian',
                'lat' => 31.8246,
                'lng' => 72.8012,
            ],
            [
                'name' => 'Landi Kotal',
                'slug' => 'landi-kotal',
                'lat' => 34.0988,
                'lng' => 71.1411,
            ],
            [
                'name' => 'Larkana',
                'slug' => 'larkana',
                'lat' => 27.5590,
                'lng' => 68.2120,
            ],
            [
                'name' => 'Layyah',
                'slug' => 'layyah',
                'lat' => 30.9613,
                'lng' => 70.9390,
            ],
            [
                'name' => 'Liliani',
                'slug' => 'liliani',
                'lat' => 32.2039,
                'lng' => 72.9512,
            ],
            [
                'name' => 'Lodhran',
                'slug' => 'lodhran',
                'lat' => 29.5339,
                'lng' => 71.6324,
            ],
            [
                'name' => 'Loralai',
                'slug' => 'loralai',
                'lat' => 30.3705,
                'lng' => 68.5980,
            ],
            [
                'name' => 'Mach',
                'slug' => 'mach',
                'lat' => 29.8637,
                'lng' => 67.3302,
            ],
            [
                'name' => 'Madeji',
                'slug' => 'madeji',
                'lat' => 27.7531,
                'lng' => 68.4517,
            ],
            [
                'name' => 'Mailsi',
                'slug' => 'mailsi',
                'lat' => 29.8012,
                'lng' => 72.1740,
            ],
            [
                'name' => 'Malakand',
                'slug' => 'malakand',
                'lat' => 34.5656,
                'lng' => 71.9304,
            ],
            [
                'name' => 'Malakwal',
                'slug' => 'malakwal',
                'lat' => 32.5545,
                'lng' => 73.2127,
            ],
            [
                'name' => 'Malakwal City',
                'slug' => 'malakwal-city',
                'lat' => 32.5549,
                'lng' => 73.2122,
            ],
            [
                'name' => 'Malir Cantonment',
                'slug' => 'malir-cantonment',
                'lat' => 24.9434,
                'lng' => 67.2059,
            ],
            [
                'name' => 'Mamu Kanjan',
                'slug' => 'mamu-kanjan',
                'lat' => 30.8304,
                'lng' => 72.7994,
            ],
            [
                'name' => 'Mananwala',
                'slug' => 'mananwala',
                'lat' => 31.5880,
                'lng' => 73.6893,
            ],
            [
                'name' => 'Mandi Bahauddin',
                'slug' => 'mandi-bahauddin',
                'lat' => 32.5870,
                'lng' => 73.4912,
            ],
            [
                'name' => 'Mangla',
                'slug' => 'mangla',
                'lat' => 31.8931,
                'lng' => 72.3817,
            ],
            [
                'name' => 'Mankera',
                'slug' => 'mankera',
                'lat' => 31.3877,
                'lng' => 71.4405,
            ],
            [
                'name' => 'Mansehra',
                'slug' => 'mansehra',
                'lat' => 34.3302,
                'lng' => 73.1968,
            ],
            [
                'name' => 'Mastung',
                'slug' => 'mastung',
                'lat' => 29.7997,
                'lng' => 66.8455,
            ],
            [
                'name' => 'Matiari',
                'slug' => 'matiari',
                'lat' => 25.5971,
                'lng' => 68.4467,
            ],
            [
                'name' => 'Matli',
                'slug' => 'matli',
                'lat' => 25.0429,
                'lng' => 68.6559,
            ],
            [
                'name' => 'Mehar',
                'slug' => 'mehar',
                'lat' => 27.1803,
                'lng' => 67.8205,
            ],
            [
                'name' => 'Mehmand Chak',
                'slug' => 'mehmand-chak',
                'lat' => 32.7852,
                'lng' => 73.8231,
            ],
            [
                'name' => 'Mehrabpur',
                'slug' => 'mehrabpur',
                'lat' => 28.1077,
                'lng' => 68.0255,
            ],
            [
                'name' => 'Mian Channun',
                'slug' => 'mian-channun',
                'lat' => 30.4407,
                'lng' => 72.3568,
            ],
            [
                'name' => 'Mianke Mor',
                'slug' => 'mianke-mor',
                'lat' => 31.2024,
                'lng' => 73.9486,
            ],
            [
                'name' => 'Mianwali',
                'slug' => 'mianwali',
                'lat' => 32.5776,
                'lng' => 71.5285,
            ],
            [
                'name' => 'Minchianabad',
                'slug' => 'minchianabad',
                'lat' => 30.1636,
                'lng' => 73.5686,
            ],
            [
                'name' => 'Mingora',
                'slug' => 'mingora',
                'lat' => 34.7795,
                'lng' => 72.3627,
            ],
            [
                'name' => 'Miran Shah',
                'slug' => 'miran-shah',
                'lat' => 33.0006,
                'lng' => 70.0712,
            ],
            [
                'name' => 'Miro Khan',
                'slug' => 'miro-khan',
                'lat' => 27.7599,
                'lng' => 68.0920,
            ],
            [
                'name' => 'Mirpur Bhtoro',
                'slug' => 'mirpur-bhtoro',
                'lat' => 24.7285,
                'lng' => 68.2601,
            ],
            [
                'name' => 'Mirpur Mathelo',
                'slug' => 'mirpur-mathelo',
                'lat' => 28.0214,
                'lng' => 69.5491,
            ],
            [
                'name' => 'Mirpur Sakro',
                'slug' => 'mirpur-sakro',
                'lat' => 24.5469,
                'lng' => 67.6280,
            ],
            [
                'name' => 'Mirwah Gorchani',
                'slug' => 'mirwah-gorchani',
                'lat' => 25.3098,
                'lng' => 69.0502,
            ],
            [
                'name' => 'Mitha Tiwana',
                'slug' => 'mitha-tiwana',
                'lat' => 32.2454,
                'lng' => 72.1062,
            ],
            [
                'name' => 'Mithi',
                'slug' => 'mithi',
                'lat' => 24.7370,
                'lng' => 69.7971,
            ],
            [
                'name' => 'Moro',
                'slug' => 'moro',
                'lat' => 26.6632,
                'lng' => 68.0002,
            ],
            [
                'name' => 'Moza Shahwala',
                'slug' => 'moza-shahwala',
                'lat' => 30.8056,
                'lng' => 70.8491,
            ],
            [
                'name' => 'Muridke',
                'slug' => 'muridke',
                'lat' => 31.8026,
                'lng' => 74.2577,
            ],
            [
                'name' => 'Murree',
                'slug' => 'murree',
                'lat' => 33.9084,
                'lng' => 73.3903,
            ],
            [
                'name' => 'Musa Khel Bazar',
                'slug' => 'musa-khel-bazar',
                'lat' => 30.8594,
                'lng' => 69.8221,
            ],
            [
                'name' => 'Mustafābād',
                'slug' => 'mustafabad',
                'lat' => 30.8922,
                'lng' => 73.4989,
            ],
            [
                'name' => 'Muzaffargarh',
                'slug' => 'muzaffargarh',
                'lat' => 30.0726,
                'lng' => 71.1938,
            ],
            [
                'name' => 'Muzaffarābād',
                'slug' => 'muzaffarabad',
                'lat' => 34.3700,
                'lng' => 73.4708,
            ],
            [
                'name' => 'Nabisar',
                'slug' => 'nabisar',
                'lat' => 25.0672,
                'lng' => 69.6434,
            ],
            [
                'name' => 'Nankana Sahib',
                'slug' => 'nankana-sahib',
                'lat' => 31.4501,
                'lng' => 73.7065,
            ],
            [
                'name' => 'Narang Mandi',
                'slug' => 'narang-mandi',
                'lat' => 31.9038,
                'lng' => 74.5159,
            ],
            [
                'name' => 'Narowal',
                'slug' => 'narowal',
                'lat' => 32.1020,
                'lng' => 74.8730,
            ],
            [
                'name' => 'Nasirabad',
                'slug' => 'nasirabad',
                'lat' => 27.3814,
                'lng' => 67.9164,
            ],
            [
                'name' => 'Naudero',
                'slug' => 'naudero',
                'lat' => 27.6668,
                'lng' => 68.3609,
            ],
            [
                'name' => 'Naukot',
                'slug' => 'naukot',
                'lat' => 24.8582,
                'lng' => 69.4015,
            ],
            [
                'name' => 'Naushahra Virkan',
                'slug' => 'naushahra-virkan',
                'lat' => 31.9626,
                'lng' => 73.9712,
            ],
            [
                'name' => 'Naushahro Firoz',
                'slug' => 'naushahro-firoz',
                'lat' => 26.8401,
                'lng' => 68.1227,
            ],
            [
                'name' => 'Nawabshah',
                'slug' => 'nawabshah',
                'lat' => 26.2394,
                'lng' => 68.4037,
            ],
            [
                'name' => 'Nazir Town',
                'slug' => 'nazir-town',
                'lat' => 33.3061,
                'lng' => 73.4833,
            ],
            [
                'name' => 'New Bādāh',
                'slug' => 'new-badah',
                'lat' => 27.3417,
                'lng' => 68.0319,
            ],
            [
                'name' => 'New Mirpur',
                'slug' => 'new-mirpur',
                'lat' => 33.1478,
                'lng' => 73.7519,
            ],
            [
                'name' => 'Noorabad',
                'slug' => 'noorabad',
                'lat' => 34.2520,
                'lng' => 71.9666,
            ],
            [
                'name' => 'Nowshera',
                'slug' => 'nowshera',
                'lat' => 34.0158,
                'lng' => 71.9812,
            ],
            [
                'name' => 'Nowshera Cantonment',
                'slug' => 'nowshera-cantonment',
                'lat' => 33.9983,
                'lng' => 71.9983,
            ],
            [
                'name' => 'Nushki',
                'slug' => 'nushki',
                'lat' => 29.5522,
                'lng' => 66.0229,
            ],
            [
                'name' => 'Okara',
                'slug' => 'okara',
                'lat' => 30.8103,
                'lng' => 73.4516,
            ],
            [
                'name' => 'Ormara',
                'slug' => 'ormara',
                'lat' => 25.2088,
                'lng' => 64.6357,
            ],
            [
                'name' => 'Pabbi',
                'slug' => 'pabbi',
                'lat' => 34.0097,
                'lng' => 71.7945,
            ],
            [
                'name' => 'Pad Idan',
                'slug' => 'pad-idan',
                'lat' => 26.7746,
                'lng' => 68.3009,
            ],
            [
                'name' => 'Paharpur',
                'slug' => 'paharpur',
                'lat' => 32.1050,
                'lng' => 70.9706,
            ],
            [
                'name' => 'Pakpattan',
                'slug' => 'pakpattan',
                'lat' => 30.3431,
                'lng' => 73.3894,
            ],
            [
                'name' => 'Panjgur',
                'slug' => 'panjgur',
                'lat' => 26.9719,
                'lng' => 64.0946,
            ],
            [
                'name' => 'Pano Aqil',
                'slug' => 'pano-aqil',
                'lat' => 27.8562,
                'lng' => 69.1111,
            ],
            [
                'name' => 'Parachinar',
                'slug' => 'parachinar',
                'lat' => 33.8997,
                'lng' => 70.1001,
            ],
            [
                'name' => 'Pasni',
                'slug' => 'pasni',
                'lat' => 25.2630,
                'lng' => 63.4692,
            ],
            [
                'name' => 'Pasrur',
                'slug' => 'pasrur',
                'lat' => 32.2629,
                'lng' => 74.6633,
            ],
            [
                'name' => 'Pattoki',
                'slug' => 'pattoki',
                'lat' => 31.0202,
                'lng' => 73.8533,
            ],
            [
                'name' => 'Phalia',
                'slug' => 'phalia',
                'lat' => 32.4310,
                'lng' => 73.5790,
            ],
            [
                'name' => 'Pind Dadan Khan',
                'slug' => 'pind-dadan-khan',
                'lat' => 32.5866,
                'lng' => 73.0446,
            ],
            [
                'name' => 'Pindi Bhattian',
                'slug' => 'pindi-bhattian',
                'lat' => 31.8984,
                'lng' => 73.2734,
            ],
            [
                'name' => 'Pindi Gheb',
                'slug' => 'pindi-gheb',
                'lat' => 33.2410,
                'lng' => 72.2648,
            ],
            [
                'name' => 'Pir Jo Goth',
                'slug' => 'pir-jo-goth',
                'lat' => 27.5918,
                'lng' => 68.6185,
            ],
            [
                'name' => 'Pir Mahal',
                'slug' => 'pir-mahal',
                'lat' => 30.7666,
                'lng' => 72.4346,
            ],
            [
                'name' => 'Pishin',
                'slug' => 'pishin',
                'lat' => 30.5818,
                'lng' => 66.9941,
            ],
            [
                'name' => 'Pithoro',
                'slug' => 'pithoro',
                'lat' => 25.5112,
                'lng' => 69.3780,
            ],
            [
                'name' => 'Qadirpur Ran',
                'slug' => 'qadirpur-ran',
                'lat' => 30.2918,
                'lng' => 71.6716,
            ],
            [
                'name' => 'Qila Abdullah',
                'slug' => 'qila-abdullah',
                'lat' => 30.7280,
                'lng' => 66.6612,
            ],
            [
                'name' => 'Qila Saifullah',
                'slug' => 'qila-saifullah',
                'lat' => 30.7008,
                'lng' => 68.3598,
            ],
            [
                'name' => 'Rahim Yar Khan',
                'slug' => 'rahim-yar-khan',
                'lat' => 28.4199,
                'lng' => 70.3035,
            ],
            [
                'name' => 'Raiwind',
                'slug' => 'raiwind',
                'lat' => 31.2490,
                'lng' => 74.2153,
            ],
            [
                'name' => 'Raja Jang',
                'slug' => 'raja-jang',
                'lat' => 31.2208,
                'lng' => 74.2548,
            ],
            [
                'name' => 'Rajanpur',
                'slug' => 'rajanpur',
                'lat' => 29.1041,
                'lng' => 70.3297,
            ],
            [
                'name' => 'Rajo Khanani',
                'slug' => 'rajo-khanani',
                'lat' => 24.9839,
                'lng' => 68.8537,
            ],
            [
                'name' => 'Ranipur',
                'slug' => 'ranipur',
                'lat' => 27.2872,
                'lng' => 68.5062,
            ],
            [
                'name' => 'Rasulnagar',
                'slug' => 'rasulnagar',
                'lat' => 32.3279,
                'lng' => 73.7804,
            ],
            [
                'name' => 'Ratodero',
                'slug' => 'ratodero',
                'lat' => 27.8023,
                'lng' => 68.2890,
            ],
            [
                'name' => 'Rawala Kot',
                'slug' => 'rawala-kot',
                'lat' => 33.8578,
                'lng' => 73.7604,
            ],
            [
                'name' => 'Renala Khurd',
                'slug' => 'renala-khurd',
                'lat' => 30.8788,
                'lng' => 73.5986,
            ],
            [
                'name' => 'Risalpur Cantonment',
                'slug' => 'risalpur-cantonment',
                'lat' => 34.0605,
                'lng' => 71.9928,
            ],
            [
                'name' => 'Rohri',
                'slug' => 'rohri',
                'lat' => 27.6920,
                'lng' => 68.8950,
            ],
            [
                'name' => 'Rojhan',
                'slug' => 'rojhan',
                'lat' => 28.6874,
                'lng' => 69.9535,
            ],
            [
                'name' => 'Rustam',
                'slug' => 'rustam',
                'lat' => 27.9671,
                'lng' => 68.8039,
            ],
            [
                'name' => 'Saddiqabad',
                'slug' => 'saddiqabad',
                'lat' => 28.3091,
                'lng' => 70.1265,
            ],
            [
                'name' => 'Sahiwal',
                'slug' => 'sahiwal',
                'lat' => 30.6660,
                'lng' => 73.1019,
            ],
            [
                'name' => 'Sahiwal',
                'slug' => 'sahiwal-punjab',
                'lat' => 31.9739,
                'lng' => 72.3311,
            ],
            [
                'name' => 'Saidu Sharif',
                'slug' => 'saidu-sharif',
                'lat' => 34.7466,
                'lng' => 72.3557,
            ],
            [
                'name' => 'Sakrand',
                'slug' => 'sakrand',
                'lat' => 26.1385,
                'lng' => 68.2744,
            ],
            [
                'name' => 'Samaro',
                'slug' => 'samaro',
                'lat' => 25.2814,
                'lng' => 69.3962,
            ],
            [
                'name' => 'Sambrial',
                'slug' => 'sambrial',
                'lat' => 32.4784,
                'lng' => 74.3534,
            ],
            [
                'name' => 'Sanghar',
                'slug' => 'sanghar',
                'lat' => 26.0469,
                'lng' => 68.9492,
            ],
            [
                'name' => 'Sangla Hill',
                'slug' => 'sangla-hill',
                'lat' => 31.7167,
                'lng' => 73.3833,
            ],
            [
                'name' => 'Sanjwal',
                'slug' => 'sanjwal',
                'lat' => 33.7611,
                'lng' => 72.4332,
            ],
            [
                'name' => 'Sann',
                'slug' => 'sann',
                'lat' => 26.0403,
                'lng' => 68.1376,
            ],
            [
                'name' => 'Sarai Alamgir',
                'slug' => 'sarai-alamgir',
                'lat' => 32.9050,
                'lng' => 73.7552,
            ],
            [
                'name' => 'Sarai Naurang',
                'slug' => 'sarai-naurang',
                'lat' => 32.8258,
                'lng' => 70.7811,
            ],
            [
                'name' => 'Sarai Sidhu',
                'slug' => 'sarai-sidhu',
                'lat' => 30.5948,
                'lng' => 71.9699,
            ],
            [
                'name' => 'Sehwan',
                'slug' => 'sehwan',
                'lat' => 26.4250,
                'lng' => 67.8613,
            ],
            [
                'name' => 'Setharja Old',
                'slug' => 'setharja-old',
                'lat' => 27.2127,
                'lng' => 68.4688,
            ],
            [
                'name' => 'Shabqadar',
                'slug' => 'shabqadar',
                'lat' => 34.2160,
                'lng' => 71.5548,
            ],
            [
                'name' => 'Shahdad Kot',
                'slug' => 'shahdad-kot',
                'lat' => 27.8473,
                'lng' => 67.9068,
            ],
            [
                'name' => 'Shahdadpur',
                'slug' => 'shahdadpur',
                'lat' => 25.9254,
                'lng' => 68.6228,
            ],
            [
                'name' => 'Shahkot',
                'slug' => 'shahkot',
                'lat' => 31.5709,
                'lng' => 73.4853,
            ],
            [
                'name' => 'Shahpur',
                'slug' => 'shahpur',
                'lat' => 32.2682,
                'lng' => 72.4688,
            ],
            [
                'name' => 'Shahpur Chakar',
                'slug' => 'shahpur-chakar',
                'lat' => 26.1541,
                'lng' => 68.6501,
            ],
            [
                'name' => 'Shahr Sultan',
                'slug' => 'shahr-sultan',
                'lat' => 29.5752,
                'lng' => 71.0221,
            ],
            [
                'name' => 'Shakargarh',
                'slug' => 'shakargarh',
                'lat' => 32.2636,
                'lng' => 75.1601,
            ],
            [
                'name' => 'Sharqpur Sharif',
                'slug' => 'sharqpur-sharif',
                'lat' => 31.4612,
                'lng' => 74.1009,
            ],
            [
                'name' => 'Shikarpur',
                'slug' => 'shikarpur',
                'lat' => 27.9556,
                'lng' => 68.6382,
            ],
            [
                'name' => 'Shingli Bala',
                'slug' => 'shingli-bala',
                'lat' => 34.6787,
                'lng' => 72.9849,
            ],
            [
                'name' => 'Shinpokh',
                'slug' => 'shinpokh',
                'lat' => 34.3296,
                'lng' => 71.1785,
            ],
            [
                'name' => 'Shorkot',
                'slug' => 'shorkot',
                'lat' => 31.9102,
                'lng' => 70.8776,
            ],
            [
                'name' => 'Shujaabad',
                'slug' => 'shujaabad',
                'lat' => 29.8809,
                'lng' => 71.2934,
            ],
            [
                'name' => 'Sibi',
                'slug' => 'sibi',
                'lat' => 29.5430,
                'lng' => 67.8773,
            ],
            [
                'name' => 'Sillanwali',
                'slug' => 'sillanwali',
                'lat' => 31.8254,
                'lng' => 72.5406,
            ],
            [
                'name' => 'Sinjhoro',
                'slug' => 'sinjhoro',
                'lat' => 26.0301,
                'lng' => 68.8087,
            ],
            [
                'name' => 'Skardu',
                'slug' => 'skardu',
                'lat' => 35.2979,
                'lng' => 75.6337,
            ],
            [
                'name' => 'Sobhodero',
                'slug' => 'sobhodero',
                'lat' => 27.3048,
                'lng' => 68.3972,
            ],
            [
                'name' => 'Sodhri',
                'slug' => 'sodhri',
                'lat' => 32.4621,
                'lng' => 74.1821,
            ],
            [
                'name' => 'Sohbatpur',
                'slug' => 'sohbatpur',
                'lat' => 28.5204,
                'lng' => 68.5430,
            ],
            [
                'name' => 'Sukheke Mandi',
                'slug' => 'sukheke-mandi',
                'lat' => 31.8654,
                'lng' => 73.5088,
            ],
            [
                'name' => 'Surab',
                'slug' => 'surab',
                'lat' => 28.4928,
                'lng' => 66.2600,
            ],
            [
                'name' => 'Surkhpur',
                'slug' => 'surkhpur',
                'lat' => 32.7182,
                'lng' => 74.4477,
            ],
            [
                'name' => 'Swabi',
                'slug' => 'swabi',
                'lat' => 34.1202,
                'lng' => 72.4698,
            ],
            [
                'name' => 'Sīta Road',
                'slug' => 'sita-road',
                'lat' => 27.0333,
                'lng' => 67.8500,
            ],
            [
                'name' => 'Talagang',
                'slug' => 'talagang',
                'lat' => 32.9277,
                'lng' => 72.4159,
            ],
            [
                'name' => 'Talamba',
                'slug' => 'talamba',
                'lat' => 30.5269,
                'lng' => 72.2408,
            ],
            [
                'name' => 'Talhar',
                'slug' => 'talhar',
                'lat' => 24.8845,
                'lng' => 68.8144,
            ],
            [
                'name' => 'Tandlianwala',
                'slug' => 'tandlianwala',
                'lat' => 31.0336,
                'lng' => 73.1327,
            ],
            [
                'name' => 'Tando Adam',
                'slug' => 'tando-adam',
                'lat' => 25.7682,
                'lng' => 68.6620,
            ],
            [
                'name' => 'Tando Allahyar',
                'slug' => 'tando-allahyar',
                'lat' => 25.4605,
                'lng' => 68.7175,
            ],
            [
                'name' => 'Tando Bago',
                'slug' => 'tando-bago',
                'lat' => 24.7891,
                'lng' => 68.9654,
            ],
            [
                'name' => 'Tando Jam',
                'slug' => 'tando-jam',
                'lat' => 25.4281,
                'lng' => 68.5292,
            ],
            [
                'name' => 'Tando Mitha Khan',
                'slug' => 'tando-mitha-khan',
                'lat' => 25.9963,
                'lng' => 69.2025,
            ],
            [
                'name' => 'Tando Muhammad Khan',
                'slug' => 'tando-muhammad-khan',
                'lat' => 25.1238,
                'lng' => 68.5368,
            ],
            [
                'name' => 'Tangi',
                'slug' => 'tangi',
                'lat' => 34.3009,
                'lng' => 71.6524,
            ],
            [
                'name' => 'Tangwani',
                'slug' => 'tangwani',
                'lat' => 28.2789,
                'lng' => 68.9976,
            ],
            [
                'name' => 'Tank',
                'slug' => 'tank',
                'lat' => 32.2171,
                'lng' => 70.3832,
            ],
            [
                'name' => 'Taunsa',
                'slug' => 'taunsa',
                'lat' => 30.7036,
                'lng' => 70.6505,
            ],
            [
                'name' => 'Thal',
                'slug' => 'thal',
                'lat' => 35.4784,
                'lng' => 72.2438,
            ],
            [
                'name' => 'Tharu Shah',
                'slug' => 'tharu-shah',
                'lat' => 26.9423,
                'lng' => 68.1176,
            ],
            [
                'name' => 'Thatta',
                'slug' => 'thatta',
                'lat' => 24.7475,
                'lng' => 67.9235,
            ],
            [
                'name' => 'Thul',
                'slug' => 'thul',
                'lat' => 28.2403,
                'lng' => 68.7755,
            ],
            [
                'name' => 'Timargara',
                'slug' => 'timargara',
                'lat' => 34.8266,
                'lng' => 71.8442,
            ],
            [
                'name' => 'Toba Tek Singh',
                'slug' => 'toba-tek-singh',
                'lat' => 30.9713,
                'lng' => 72.4828,
            ],
            [
                'name' => 'Topi',
                'slug' => 'topi',
                'lat' => 34.0703,
                'lng' => 72.6215,
            ],
            [
                'name' => 'Turbat',
                'slug' => 'turbat',
                'lat' => 26.0012,
                'lng' => 63.0485,
            ],
            [
                'name' => 'Ubauro',
                'slug' => 'ubauro',
                'lat' => 28.1643,
                'lng' => 69.7311,
            ],
            [
                'name' => 'Umarkot',
                'slug' => 'umarkot',
                'lat' => 25.3633,
                'lng' => 69.7418,
            ],
            [
                'name' => 'Upper Dir',
                'slug' => 'upper-dir',
                'lat' => 35.2074,
                'lng' => 71.8768,
            ],
            [
                'name' => 'Usta Muhammad',
                'slug' => 'usta-muhammad',
                'lat' => 28.1772,
                'lng' => 68.0437,
            ],
            [
                'name' => 'Uthal',
                'slug' => 'uthal',
                'lat' => 25.8072,
                'lng' => 66.6219,
            ],
            [
                'name' => 'Utmanzai',
                'slug' => 'utmanzai',
                'lat' => 34.1878,
                'lng' => 71.7627,
            ],
            [
                'name' => 'Vihari',
                'slug' => 'vihari',
                'lat' => 30.0445,
                'lng' => 72.3556,
            ],
            [
                'name' => 'Wana',
                'slug' => 'wana',
                'lat' => 32.2989,
                'lng' => 69.5725,
            ],
            [
                'name' => 'Warah',
                'slug' => 'warah',
                'lat' => 27.4481,
                'lng' => 67.7965,
            ],
            [
                'name' => 'Wazirabad',
                'slug' => 'wazirabad',
                'lat' => 32.4432,
                'lng' => 74.1200,
            ],
            [
                'name' => 'Yazman',
                'slug' => 'yazman',
                'lat' => 29.1212,
                'lng' => 71.7446,
            ],
            [
                'name' => 'Zafarwal',
                'slug' => 'zafarwal',
                'lat' => 32.3446,
                'lng' => 74.8999,
            ],
            [
                'name' => 'Zahir Pir',
                'slug' => 'zahir-pir',
                'lat' => 28.8128,
                'lng' => 70.5234,
            ],
            [
                'name' => 'Zaida',
                'slug' => 'zaida',
                'lat' => 34.0595,
                'lng' => 72.4669,
            ],
            [
                'name' => 'Zhob',
                'slug' => 'zhob',
                'lat' => 31.3408,
                'lng' => 69.4493,
            ],
            [
                'name' => 'Ziarat',
                'slug' => 'ziarat',
                'lat' => 30.3824,
                'lng' => 67.7256,
            ],
        ];
    }
}