<div>
    <div class="app-content-header">
        <div class="container-fluid">
            <div class="row"><div class="col-sm-6"><h1 class="mb-0 fs-3">Projects</h1></div><div class="col-sm-6"><ol class="breadcrumb float-sm-end"><li class="breadcrumb-item"><a href="<?php echo e(route('admin.dashboard')); ?>">Home</a></li><li class="breadcrumb-item active">Projects</li></ol></div></div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row g-3 mb-3">
            <div class="col-6 col-md-3"><div class="card border-0 shadow-sm bg-primary text-white"><div class="card-body text-center py-3"><i class="bi bi-briefcase display-6"></i><h3 class="mb-0 mt-1"><?php echo e($totalProjects); ?></h3><small>Total</small></div></div></div>
            <div class="col-6 col-md-3"><div class="card border-0 shadow-sm bg-success text-white"><div class="card-body text-center py-3"><i class="bi bi-check-circle display-6"></i><h3 class="mb-0 mt-1"><?php echo e($activeProjects); ?></h3><small>Active</small></div></div></div>
            <div class="col-6 col-md-3"><div class="card border-0 shadow-sm bg-warning text-white"><div class="card-body text-center py-3"><i class="bi bi-star-fill display-6"></i><h3 class="mb-0 mt-1"><?php echo e($featuredProjects); ?></h3><small>Featured</small></div></div></div>
            <div class="col-6 col-md-3"><div class="card border-0 shadow-sm bg-info text-white"><div class="card-body text-center py-3"><i class="bi bi-building-check display-6"></i><h3 class="mb-0 mt-1"><?php echo e($completedProjects); ?></h3><small>Completed</small></div></div></div>
        </div>

        <div class="card shadow-sm border-0 mb-3">
            <div class="card-body">
                <div class="row g-2 align-items-end">
                    <div class="col-md-3"><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input type="text" class="form-control" wire:model.blur="search" placeholder="Search..."><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($search): ?><button class="btn btn-outline-secondary" wire:click="clearSearch"><i class="bi bi-x-lg"></i></button><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div>
                    <div class="col-6 col-md-2"><select class="form-select" wire:model.blur="statusFilter"><option value="">Status</option><option value="completed">Completed</option><option value="ongoing">Ongoing</option><option value="planning">Planning</option><option value="on-hold">On Hold</option></select></div>
                    <div class="col-6 col-md-2"><select class="form-select" wire:model.blur="categoryFilter"><option value="">Category</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $c): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($c->id); ?>"><?php echo e($c->pc_name); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></div>
                    <div class="col-6 col-md-2"><select class="form-select" wire:model.blur="featuredFilter"><option value="">Featured</option><option value="1">Yes</option><option value="0">No</option></select></div>
                    <div class="col-6 col-md-3 text-end"><button class="btn btn-outline-secondary me-1" wire:click="clearFilters"><i class="bi bi-funnel"></i></button><a href="<?php echo e(route('admin.projects.create')); ?>" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Add Project</a></div>
                </div>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(count($selectedProjects) > 0): ?><div class="mt-3 p-2 bg-light rounded d-flex gap-2"><span class="fw-semibold"><?php echo e(count($selectedProjects)); ?> selected</span><button class="btn btn-sm btn-success" wire:click="bulkActivate"><i class="bi bi-check-circle"></i> Activate</button><button class="btn btn-sm btn-warning" wire:click="bulkDeactivate"><i class="bi bi-pause-circle"></i> Deactivate</button><button class="btn btn-sm btn-danger" wire:click="bulkDelete"><i class="bi bi-trash"></i> Delete</button></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
            </div>
        </div>

        <div class="row g-3">
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
            <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
                <div class="card shadow-sm border-0 h-100 project-card">
                    <div class="position-relative">
                        <img src="<?php echo e($project->image_url); ?>" class="card-img-top" style="height:180px;object-fit:cover;">
                        <div class="position-absolute top-0 start-0 m-2"><input type="checkbox" class="form-check-input" <?php if(in_array($project->id, $selectedProjects)): echo 'checked'; endif; ?> wire:click="toggleProjectSelection(<?php echo e($project->id); ?>)" style="width:20px;height:20px;background:white;"></div>
                        <div class="position-absolute top-0 end-0 m-2 d-flex gap-1"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($project->is_featured): ?><span class="badge bg-warning"><i class="bi bi-star-fill"></i></span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><?php echo $project->status_badge; ?></div>
                    </div>
                    <div class="card-body d-flex flex-column">
                        <h6 class="fw-bold"><?php echo e(Str::limit($project->p_title, 35)); ?></h6>
                        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($project->category): ?><small class="text-muted"><?php echo e($project->category->pc_name); ?></small><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        <div class="mt-1 small text-muted">
                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($project->p_client): ?><div><i class="bi bi-person"></i> <?php echo e(Str::limit($project->p_client, 25)); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($project->p_location): ?><div><i class="bi bi-geo-alt"></i> <?php echo e(Str::limit($project->p_location, 25)); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        </div>
                        <div class="mt-auto"><small class="text-muted"><?php echo e($project->formatted_start_date); ?> - <?php echo e($project->formatted_end_date); ?></small></div>
                        <div class="btn-group w-100 btn-group-sm mt-2">
                            <button class="btn btn-info" wire:click="viewProjectDetails(<?php echo e($project->id); ?>)"><i class="bi bi-eye"></i></button>
                            <a href="<?php echo e(route('admin.projects.edit', $project->id)); ?>" class="btn btn-primary"><i class="bi bi-pencil"></i></a>
                            <button class="btn btn-<?php echo e($project->is_featured ? 'warning' : 'outline-warning'); ?>" wire:click="toggleFeatured(<?php echo e($project->id); ?>)"><i class="bi bi-star"></i></button>
                            <button class="btn btn-danger" wire:click="confirmDelete(<?php echo e($project->id); ?>)"><i class="bi bi-trash"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
            <div class="col-12 text-center py-5"><i class="bi bi-briefcase display-1 text-muted d-block mb-3"></i><h4>No projects found</h4><a href="<?php echo e(route('admin.projects.create')); ?>" class="btn btn-primary mt-2"><i class="bi bi-plus-lg"></i> Add First Project</a></div>
            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </div>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($projects->hasPages()): ?><div class="card shadow-sm border-0 mt-3"><div class="card-footer d-flex justify-content-between"><small>Showing <?php echo e($projects->firstItem()); ?>-<?php echo e($projects->lastItem()); ?> of <?php echo e($projects->total()); ?></small><?php echo e($projects->links()); ?></div></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </div>

    <!-- View Modal -->
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($showViewModal && $viewProject): ?>
    <div class="modal fade show d-block" style="background:rgba(0,0,0,0.5);z-index:1055;"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header bg-primary text-white"><h5 class="modal-title"><i class="bi bi-eye"></i> Project Details</h5><button class="btn-close btn-close-white" wire:click="closeModals"></button></div><div class="modal-body"><div class="row"><div class="col-md-5"><img src="<?php echo e($viewProject->image_url); ?>" class="img-fluid rounded mb-3"><div class="d-flex gap-2 mb-2"><?php echo $viewProject->status_badge; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($viewProject->is_featured): ?><span class="badge bg-warning">Featured</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div><div class="col-md-7"><h4><?php echo e($viewProject->p_title); ?></h4><p><strong>Category:</strong> <?php echo e($viewProject->category->pc_name ?? $viewProject->p_category); ?></p><p><strong>Client:</strong> <?php echo e($viewProject->p_client ?: 'N/A'); ?></p><p><strong>Location:</strong> <?php echo e($viewProject->p_location ?: 'N/A'); ?></p><p><strong>Duration:</strong> <?php echo e($viewProject->formatted_start_date); ?> - <?php echo e($viewProject->formatted_end_date); ?></p></div></div></div><div class="modal-footer"><button class="btn btn-secondary" wire:click="closeModals">Close</button><a href="<?php echo e(route('admin.projects.edit', $viewProject->id)); ?>" class="btn btn-primary"><i class="bi bi-pencil"></i> Edit</a></div></div></div></div><div class="modal-backdrop fade show"></div>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>

    <!-- Delete Modal -->
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($showDeleteModal): ?>
    <div class="modal fade show d-block" style="background:rgba(0,0,0,0.5);z-index:1055;"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header bg-danger text-white"><h5 class="modal-title"><i class="bi bi-exclamation-triangle"></i> Confirm Delete</h5><button class="btn-close btn-close-white" wire:click="closeModals"></button></div><div class="modal-body text-center py-4"><i class="bi bi-trash display-3 text-danger mb-3 d-block"></i><h5>Delete this project?</h5></div><div class="modal-footer justify-content-center"><button class="btn btn-secondary" wire:click="closeModals">Cancel</button><button class="btn btn-danger" wire:click="deleteProject"><i class="bi bi-trash"></i> Delete</button></div></div></div></div><div class="modal-backdrop fade show"></div>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div>

<?php $__env->startPush('styles'); ?>
<style>.project-card{transition:all .3s ease}.project-card:hover{transform:translateY(-5px);box-shadow:0 10px 30px rgba(0,0,0,.15)!important}.form-switch .form-check-input{width:3em;height:1.5em;cursor:pointer}</style>
<?php $__env->stopPush(); ?><?php /**PATH /var/www/html/projects/saif/razzaq-engineering/resources/views/livewire/admin/projects/project-list.blade.php ENDPATH**/ ?>