<?php echo '<'.'?xml version="1.0" encoding="UTF-8"?'.'>'; ?>

<?xml-stylesheet type="text/xsl" href="<?php echo e(asset('sitemap-index.xsl')); ?>" ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
              http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd">

    <!-- Generated by Razzaq Engineering Services -->
    <!-- Sitemap Index - Total Sitemaps: <?php echo e(count($sitemaps)); ?> -->
    <!-- Last Modified: <?php echo e(now()->toAtomString()); ?> -->

    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $sitemaps; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $sitemap): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
    <sitemap>
        <loc><?php echo e(htmlspecialchars($sitemap['loc'], ENT_XML1, 'UTF-8')); ?></loc>
        
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(isset($sitemap['lastmod'])): ?>
        <lastmod><?php echo e($sitemap['lastmod']); ?></lastmod>
        <?php else: ?>
        <lastmod><?php echo e(now()->toDateString()); ?></lastmod>
        <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </sitemap>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>

</sitemapindex><?php /**PATH /var/www/html/projects/saif/razzaq-engineering/resources/views/livewire/website/sitemap-index-page.blade.php ENDPATH**/ ?>