{!! '<'.'?xml version="1.0" encoding="UTF-8"?'.'>' !!}
{{-- <?xml-stylesheet type="text/xsl" href="{{ asset('sitemap.xsl') }}" ?> --}}
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
        xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

    <!-- Generated by Razzaq Engineering Services -->
    <!-- Total URLs: {{ count($urls) }} -->
    <!-- Last Modified: {{ $lastModified }} -->

    @foreach($urls as $url)
    <url>
        <loc>{{ htmlspecialchars($url['loc'], ENT_XML1, 'UTF-8') }}</loc>
        
        @if(isset($url['lastmod']))
        <lastmod>{{ $url['lastmod'] }}</lastmod>
        @endif
        
        @if(isset($url['changefreq']))
        <changefreq>{{ $url['changefreq'] }}</changefreq>
        @else
        <changefreq>monthly</changefreq>
        @endif
        
        @if(isset($url['priority']))
        <priority>{{ $url['priority'] }}</priority>
        @else
        <priority>0.5</priority>
        @endif
        
        <mobile:mobile/>

        @if(isset($url['images']) && count($url['images']) > 0)
            @foreach($url['images'] as $image)
            <image:image>
                <image:loc>{{ htmlspecialchars($image['loc'], ENT_XML1, 'UTF-8') }}</image:loc>
                @if(isset($image['caption']))
                <image:caption>{{ htmlspecialchars($image['caption'], ENT_XML1, 'UTF-8') }}</image:caption>
                @endif
                @if(isset($image['title']))
                <image:title>{{ htmlspecialchars($image['title'], ENT_XML1, 'UTF-8') }}</image:title>
                @endif
            </image:image>
            @endforeach
        @endif
    </url>
    @endforeach

</urlset>