{!! '<'.'?xml version="1.0" encoding="UTF-8"?'.'>' !!}
<?xml-stylesheet type="text/xsl" href="{{ asset('sitemap-index.xsl') }}" ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
              http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd">

    <!-- Generated by Razzaq Engineering Services -->
    <!-- Sitemap Index - Total Sitemaps: {{ count($sitemaps) }} -->
    <!-- Last Modified: {{ now()->toAtomString() }} -->

    @foreach($sitemaps as $sitemap)
    <sitemap>
        <loc>{{ htmlspecialchars($sitemap['loc'], ENT_XML1, 'UTF-8') }}</loc>
        
        @if(isset($sitemap['lastmod']))
        <lastmod>{{ $sitemap['lastmod'] }}</lastmod>
        @else
        <lastmod>{{ now()->toDateString() }}</lastmod>
        @endif
    </sitemap>
    @endforeach

</sitemapindex>